config/routes.rb
Rails.application.routes.draw do

  get 'sessions/logout' , as: :logout

  namespace :admin do
    root 'base#index'
    resources :users do
      resources :permissions
      put "permissions", to: "permissions#set", as: "set_permissions"
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  
  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
      member do
        post :watch
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tickets
      end
    end
  end

  resources :users, :sessions, :files

  root 'projects#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets, dependent: :delete_all
  validates :name, presence: true

  has_many :permissions, as: :thing

  scope :viewable_by, ->(user) do
    joins(:permissions).where(permissions: { action: 'view', user_id: user.id })
  end

  scope :for, ->(user) do
    user.admin? ? Project.all : Project.viewable_by(user)
  end

  def last_ticket
    tickets.last
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::BaseController
  before_action :authorize_admin, only: [:create, :update, :destroy]
  before_action :find_project, only: [:show, :update, :destroy]
  def index
    @projects = Project.for(current_user).all
    respond_to do |format|
      format.json { render json: @projects }
    end
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      respond_to do |format|
        format.json { render json: @project, location: api_v1_project_path(@project) }
      end
    else
      render json: @project.errors
    end
  end

  def show
    render json: @project, methods: "last_ticket"
  end

  def update
    if @project.update_attributes(project_params)
      render json: @project
    else
      render json: @project.errors, status: 422
    end
  end

  def destroy
    @project.destroy
    render json: @project, status: 204
  end

  private
  def project_params
    params.require(:project).permit(:name)
  end
  def authorize_admin
    if !@current_user.admin?
      error = { "error" => "You must be an admin to do that" }
      render json: error.to_json, status: 401
    end
  end
  def find_project
    @project = Project.for(current_user).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    error = { "error" => "The project could not be found" }
    render json: error.to_json, status: 404
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_admin!, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_signin!, only: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.for(current_user)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tickets = @project.tickets
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
      if @project.save
        redirect_to @project, notice: 'Project was successfully created.'
      else
        flash.now[:alert] = "Project has not been created"
        render :new
      end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
      if @project.update(project_params)
        redirect_to @project, notice: 'Project was successfully updated.'
      else
        flash.now[:alert] = "Project has not been updated"
        render :edit
      end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project has been destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "Project could not be found"
      redirect_to projects_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to project.name, project %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% admin_only do %>
  <%= link_to 'New Project', new_project_path %>
  <%= link_to 'Admin', admin_root_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<% admin_only do %>
  <%= link_to 'Edit Project', edit_project_path(@project) %> |
  <%= link_to 'Delete Project', project_path(@project), method: :delete %> |
<% end %>
<%= link_to 'Back', projects_path %>
<div>
  <%= form_tag search_project_tickets_path(@project), method: :get do %>
    <%= label_tag 'Search' %>
    <%= text_field_tag 'Search' %>
    <%= submit_tag 'Search' %>
  <% end %>
</div>

<% authorized?("create tickets", @project) do %>
  <%= link_to "New Ticket", new_project_ticket_path(@project, @ticket) %>
<% end %>

<h2>Tickets</h2>
<ul id="tickets">
  <% @tickets.each do |t| %>
    <li><%= link_to t.title, [@project, t] %></li>
  <% end %>
</ul>