config/routes.rb
Rails.application.routes.draw do

  get 'sessions/logout' , as: :logout

  namespace :admin do
    root 'base#index'
    resources :users do
      resources :permissions
      put "permissions", to: "permissions#set", as: "set_permissions"
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  
  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
      member do
        post :watch
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tickets
      end
    end
  end

  resources :users, :sessions, :files

  root 'projects#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :create_auth_token
  has_secure_password
  has_many :tickets
  has_many :permissions
  has_many :comments
  validates :email, presence: true

  def self.reset_request_count
    update_all("request_count = 0 where request_count > 0")
  end

  def to_s
    "#{email} (#{admin ? "Admin" : "User"})"
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column == self[column])
  end

  def create_auth_token
    generate_token(:auth_token)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(:email)
  end
  def new
    @user = User.new
  end

  def show

  end

  def create
    @user = User.new(user_params)
    @user.password_confirmation = params[:password]
    if @user.save
      redirect_to admin_users_path, notice: 'User has been created'
    else
      flash.now[:alert] = 'User has not been created'
      render :new
    end
  end

  def edit
    
  end

  def update
    param = user_params
    if param[:password].blank?
      param.delete(:password)
      param.delete(:password_confirmation)
    end
    if @user.update_attributes(param)
      redirect_to admin_users_path, notice: 'User has been updated'
    else
      flash.now[:alert] = 'User has not been updated'
      render :edit
    end

  end

  def destroy
    if @user == current_user
      flash[:alert] = 'You cannot delete yourself!'
    else
      @user.destroy
      flash[:notice] = 'User has been deleted'
    end
    redirect_to admin_users_path
  end

  

  private

  def user_params
    params.require(:user).permit(:email, :admin, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      cookies[:auth_token] = @user.auth_token
      redirect_to root_path, notice: '注册成功！'
    else
      flash.now[:alert] = '注册信息有误，请重试！'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: '更新成功！'
    else
      flash.now[:alert] = '更新信息有误，请重试！'
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any?  %>
    <div id='error_explaination'>
      <h2>提交信息中存在<%=@user.errors.count %>个错误！</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email, "Email"  %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password, "Password"  %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :admin, "Is an admin?"  %>
    <%= f.check_box :admin %>
  </p>
  
  <% if @user.new_record? %>
    <%= f.submit 'Create User' %>
  <% else %>
    <%= f.submit 'Update User' %>
  <% end %>

<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>
<p>Find me in app/views/admin/users/index.html.erb</p>

<h1>New User</h1>
<%= link_to "New User", new_admin_user_path %>

<h1>Users</h1>

<ul id='users' >
  <% @users.each do |user|  %>
    <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

app/views/admin/users/new.html.erb
<h1>New User</h1>
<div>
  <%= render 'form' %>
</div>

app/views/admin/users/show.html.erb
<h2><%= @user %></h2>
<%= link_to "Edit User", edit_admin_user_path(@user) %>
<%= link_to "Delete User", admin_user_path(@user), method: :delete %>
<%= link_to "Permissions", admin_user_permissions_path(@user) %>