config/routes.rb
Rails.application.routes.draw do

  get 'sessions/logout' , as: :logout

  namespace :admin do
    root 'base#index'
    resources :users do
      resources :permissions
      put "permissions", to: "permissions#set", as: "set_permissions"
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  
  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
      member do
        post :watch
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tickets
      end
    end
  end

  resources :users, :sessions, :files

  root 'projects#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/state.rb
class State < ActiveRecord::Base
  def to_s
    name
  end

  def default!
    current_default_state = State.where(default: true).first
    self.default = true
    self.save!

    if current_default_state
      current_default_state.default = false
      current_default_state.save!
    end
  end

end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController

  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.create(state_params)
    if @state.save
      redirect_to admin_states_path, notice: 'State has been created'
    else
      flash.now[:alert] = 'State has not been created'
      render :new
    end
  end

  def make_default
    @state = State.find(params[:id])
    @state.default!
    redirect_to admin_states_path, notice: "#{@state.name} is now the default state"
  end


  private
  def state_params
    params.require(:state).permit(:name)
  end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state] do |f| %>
  <% if @state.errors.any?  %>
    <div id='error_explaination'>
      <h2>提交信息中存在<%=@state.errors.count %>个错误！</h2>
      <ul>
        <% @state.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  
  <% if @state.new_record? %>
    <%= f.submit 'Create State' %>
  <% else %>
    <%= f.submit 'Update State' %>
  <% end %>

<% end %>

app/views/admin/states/index.html.erb
<%= link_to "New State", new_admin_state_path %>

<div id='states'>
  <% @states.each do |s| %>
    <div class= "<%= s.name %>">
      <%= s.name %>
      <%= link_to "Make Default", make_default_admin_state_path(s) %>
    </div>
  <% end %>
</ul>

app/views/admin/states/new.html.erb
<h1>New State</h1>
<%= render "form" %>